image: mobiledevops/flutter-sdk-image:3.16.4

pipelines:
  pull-requests:
    '**':
      - step:
          name: Run Unit/Widget/Bloc Tests
          script:
            - flutter pub get
            - flutter test ./test